name: Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    name: 'Build ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Version
        shell: bash
        run: |
          sed -i -e "s/0.0.0-SNAPSHOT/${{ inputs.version }}/g" mix.exs

      - name: Install Elixir toolchain
        uses: erlef/setup-beam@v1
        if: ${{ runner.os != 'macOS' }}
        with:
          otp-version: '25.0.4'
          elixir-version: '1.13.4'

      - name: Install Elixir toolchain
        if: ${{ runner.os == 'macOS' }}
        run: brew install elixir         
          
      - name: Build
        run: mix escript.build
          
      - name: Assemble
        uses: jreleaser/release-action@v2
        with:
          arguments: assemble
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: artifacts
          path: |
            out/jreleaser/assemble/helloworld/archive/*.zip

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: jreleaser-${{ matrix.os }}
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
